SinExWebApp20328991/Models/Shipment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace SinExWebApp20328991.Models
{
    [Table("Shipment")]
    public class Shipment
    {
        [Key]
        public virtual int WaybillId { get; set; }
        public virtual string ReferenceNumber { get; set; }
        public virtual string ServiceType { get; set; }
        public virtual DateTime ShippedDate { get; set; }
        public virtual DateTime DeliveredDate { get; set; }
        public virtual string RecipientName { get; set; }
        public virtual int NumberOfPackages { get; set; }
        public virtual string Origin { get; set; }
        public virtual string Destination { get; set; }
        public virtual string Status { get; set; }
        public virtual int ShippingAccountId { get; set; }
        //navigation property to Shipment Account
        public virtual ShippingAccount ShippingAccount { get; set; }

    }
}

SinExWebApp20328991/Controllers/ShipmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20328991.Models;
using SinExWebApp20328991.ViewModels;
using X.PagedList;

namespace SinExWebApp20328991.Controllers
{
    public class ShipmentsController : Controller
    {
        private SinExDatabaseContext db = new SinExDatabaseContext();
        // GET: Shipments/GenerateHistoryReport
        [Authorize(Roles = "Employee,Customer")]
        public ActionResult GenerateHistoryReport(int?ShippingAccountId,DateTime? EndDate,DateTime? StartDate,DateTime? currentStartDate, DateTime? currentEndDate, string sortOrder, string currentServiceType, string currentShippedDate,string currentDeliveredDate ,string currentRecipientName,string currentOrigin ,string currentDestination,int? currentShippingAccountId,int? page)
        {
            // Instantiate an instance of the ShipmentsReportViewModel and the ShipmentsSearchViewModel.
            var shipmentSearch = new ShipmentsReportViewModel();
            shipmentSearch.Shipment = new ShipmentsSearchViewModel();

            ViewBag.CurrentSort = sortOrder;
            int pageSize=5;
            int pageNumber = (page ?? 1);
            //Retain search conditions for sorting
            if (System.Web.HttpContext.Current.User.IsInRole("Employee"))
            {
                if (ShippingAccountId == null)
                {
                    ShippingAccountId = currentShippingAccountId;
                    if (EndDate == null || StartDate == null)
                    {
                        EndDate = currentEndDate;
                        StartDate = currentStartDate;
                    }

                }
                else
                {
                    page = 1;
                }
                ViewBag.CurrentShippingAccountId = ShippingAccountId;
            }
            if (System.Web.HttpContext.Current.User.IsInRole("Customer"))
            {
                if (ShippingAccountId == null)
                {
                    string tempUserName = System.Web.HttpContext.Current.User.Identity.Name;
                    var tempShippingAccount=db.ShippingAccount.SingleOrDefault(s => s.UserName == tempUserName);
                    int tempId = tempShippingAccount.ShippingAccountId;
                    ShippingAccountId = tempId;
                    if (EndDate == null || StartDate == null)
                    {
                        EndDate = currentEndDate;
                        StartDate = currentStartDate;
                    }

                }
                else
                {
                    page = 1;
                }
                ViewBag.CurrentShippingAccountId = ShippingAccountId;
            }
            if (EndDate == null || StartDate == null)
            {
                EndDate = currentEndDate;
                StartDate = currentStartDate;
                ViewBag.CurrentEndDate = DateTime.Now.ToString("dd/mm/yyyy");
                ViewBag.CurrentStartDate = DateTime.Now.ToString("dd/mm/yyyy");
            }
            else
            {
                ViewBag.CurrentEndDate = EndDate;
                ViewBag.CurrentStartDate = StartDate;
            }
            // Populate the ShippingAccountId dropdown list.
            shipmentSearch.Shipment.ShippingAccounts = PopulateShippingAccountsDropdownList().ToList();
            if (currentShippingAccountId!=null)
            {
                shipmentSearch.Shipment.ShippingAccountId = (int)currentShippingAccountId;
            }

            // Initialize the query to retrieve shipments using the ShipmentsListViewModel.
            var shipmentQuery = from s in db.Shipments
                                select new ShipmentsListViewModel
                                {
                                    WaybillId = s.WaybillId,
                                    ServiceType = s.ServiceType,
                                    ShippedDate = s.ShippedDate,
                                    DeliveredDate = s.DeliveredDate,
                                    RecipientName = s.RecipientName,
                                    NumberOfPackages = s.NumberOfPackages,
                                    Origin = s.Origin,
                                    Destination = s.Destination,
                                    ShippingAccountId = s.ShippingAccountId
                                };

            // Add the condition to select a spefic shipping account if shipping account id is not null.
            if (ShippingAccountId != null)
            {
               
                ViewBag.ServiceTypeSortParm = sortOrder == "ServiceType" ? "ServiceType_desc" : "ServiceType";
                ViewBag.ShippedDateSortParm = sortOrder == "ShippedDate" ? "ShippedDate_desc" : "ShippedDate";
                ViewBag.DeliveredDateSortParm = sortOrder == "DeliveredDate" ? "DeliveredDate_desc" : "DeliveredDate";
                ViewBag.RecipientNameSortParm = sortOrder == "RecipientName" ? "RecipientName_desc" : "RecipientName";
                ViewBag.OriginSortParm = sortOrder == "Origin" ? "Origin_desc" : "Origin";
                ViewBag.DestinationSortParm = sortOrder == "Destination" ? "Destination_desc" : "Destination";
                switch (sortOrder)
                {
                    case "ServiceType_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.ServiceType);
                        break;
                    case "ServiceType":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.ServiceType);
                        break;
                    case "ShippedDate_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.ShippedDate);
                        break;
                    case "ShippedDate":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.ShippedDate);
                        break;
                    case "DeliveredDate_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.DeliveredDate);
                        break;
                    case "DeliveredDate":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.DeliveredDate);
                        break;
                    case "RecipientName_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.RecipientName);
                        break;
                    case "RecipientName":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.RecipientName);
                        break;
                    case "Origin_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.Origin);
                        break;
                    case "Origin":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.Origin);
                        break;
                    case "Destination_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.Destination);
                        break;
                    case "Destination":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.Destination);
                        break;
                    default:
                        shipmentQuery = shipmentQuery.OrderBy(s => s.WaybillId);
                        break;



                }
                // TODO: Construct the LINQ query to retrive only the shipments for the specified shipping account id.
                shipmentQuery = shipmentQuery.Where(s => s.ShippingAccountId == ShippingAccountId);
                if (EndDate != null &&StartDate != null)
                {
                    shipmentQuery = shipmentQuery.Where(s => (DateTime.Compare(s.ShippedDate, (DateTime)EndDate) <= 0) && (DateTime.Compare(s.DeliveredDate, (DateTime)StartDate) >= 0));
                }
                    shipmentSearch.Shipments = shipmentQuery.ToPagedList(pageNumber, pageSize);
            }
            
            else
            {
                // Return an empty result if no shipping account id has been selected.
                shipmentSearch.Shipments = new ShipmentsListViewModel[0].ToPagedList(pageNumber, pageSize);
            }

            return View(shipmentSearch);
        }

        private SelectList PopulateShippingAccountsDropdownList()
        {
            // TODO: Construct the LINQ query to retrieve the unique list of shipping account ids.
            var shippingAccountQuery = db.Shipments.Select(s=>s.ShippingAccountId).Distinct().OrderBy(s=>s);
            return new SelectList(shippingAccountQuery);
        }
        // GET: Shipments
        public ActionResult Index()
        {
            return View(db.Shipments.ToList());
        }

        // GET: Shipments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shipment shipment = db.Shipments.Find(id);
            if (shipment == null)
            {
                return HttpNotFound();
            }
            return View(shipment);
        }

        // GET: Shipments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shipments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

SinExWebApp20328991/Views/Shipments/Create.cshtml
@model SinExWebApp20328991.Models.Shipment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shipment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ReferenceNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReferenceNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReferenceNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveredDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveredDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecipientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecipientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecipientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPackages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPackages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPackages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippingAccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippingAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippingAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20328991/Views/Shipments/Delete.cshtml
@model SinExWebApp20328991.Models.Shipment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shipment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveredDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecipientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPackages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfPackages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Origin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippingAccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippingAccountId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SinExWebApp20328991/Views/Shipments/Details.cshtml
@model SinExWebApp20328991.Models.Shipment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Shipment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveredDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecipientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPackages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfPackages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Origin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippingAccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippingAccountId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WaybillId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SinExWebApp20328991/Views/Shipments/Edit.cshtml
@model SinExWebApp20328991.Models.Shipment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shipment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WaybillId)

        <div class="form-group">
            @Html.LabelFor(model => model.ReferenceNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReferenceNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReferenceNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveredDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveredDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecipientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecipientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecipientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPackages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPackages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPackages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippingAccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippingAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippingAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20328991/Views/Shipments/GenerateHistoryReport.cshtml
@model SinExWebApp20328991.ViewModels.ShipmentsReportViewModel


@{
    ViewBag.Title = "Shipment History";
}

<h2>Shipment History</h2>
@Html.Partial("_ShipmentsSearchPartial",Model.Shipment)
@Html.Partial("_ShipmentsListPartial", Model.Shipments)
@Html.Partial("_ShipmentsPagingPartial", Model.Shipments)



SinExWebApp20328991/Views/Shipments/Index.cshtml
@model IEnumerable<SinExWebApp20328991.Models.Shipment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServiceType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeliveredDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecipientName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPackages)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Origin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShippingAccountId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ReferenceNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ServiceType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShippedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeliveredDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RecipientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfPackages)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Origin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShippingAccountId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.WaybillId }) |
            @Html.ActionLink("Details", "Details", new { id=item.WaybillId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.WaybillId })
        </td>
    </tr>
}

</table>

SinExWebApp20328991/Views/Shipments/_ShipmentsPagingPartial.cshtml
@model X.PagedList.IPagedList<SinExWebApp20328991.ViewModels.ShipmentsListViewModel>
    @using X.PagedList.Mvc

@if (Model.PageCount > 1)
{
    <div class="pager">
        @Html.PagedListPager(Model, page => Url.Action("GenerateHistoryReport", new {
       page,
       sortOrder = ViewBag.CurrentSort,
       currentShippingAccountId = ViewBag.CurrentShippingAccountId,
       currentStartDate = ViewBag.CurrentStartDate,
       currentEndDate = ViewBag.CurrentEndDate,

   }))
        Page @Model.PageNumber of @Model.PageCount
    </div>
}



SinExWebApp20328991/Views/Shipments/_ShipmentsSearchPartial.cshtml
@model SinExWebApp20328991.ViewModels.ShipmentsSearchViewModel

@using (Html.BeginForm("GenerateHistoryReport", "Shipments", FormMethod.Get))
{
    if (User.IsInRole("Employee")) { 
    @Html.LabelFor(a => a.ShippingAccountId,"Shipping Account: ")
    @Html.DropDownListFor(a=> a.ShippingAccountId,Model.ShippingAccounts,"Please select")
    }
    @Html.LabelFor(a => a.StartDate, "From: ")
    @Html.TextBoxFor(a => a.StartDate, htmlAttributes:new { @Value=ViewBag.CurrentStartDate, type = "date"})
    @Html.LabelFor(a => a.EndDate, "To: ")
    @Html.TextBoxFor(a => a.EndDate, htmlAttributes: new { @Value = ViewBag.CurrentEndDate,type = "date"  } )
    <input type="submit" value="Search"/>
}
